using System.Collections.Immutable;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Feather.Generators.Diagnostics;
using Feather.Generators.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Feather.Generators;

internal static class AssetManifestWriter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<AssetTypeModel> typeModels,
        ImmutableArray<AssetContractModel> capabilityModels,
        ImmutableArray<AssetContractModel> outputModels,
        ImmutableArray<AssetProviderModel> providerModels)
    {
        if (typeModels.IsDefaultOrEmpty &&
            capabilityModels.IsDefaultOrEmpty &&
            outputModels.IsDefaultOrEmpty &&
            providerModels.IsDefaultOrEmpty)
        {
            return;
        }

        var capabilities = ValidateContracts(context, capabilityModels, AssetContractKind.Capability);
        var outputs = ValidateContracts(context, outputModels, AssetContractKind.Output);
        var providers = ValidateProviders(context, providerModels);
        var types = ValidateTypes(context, typeModels, capabilities, outputs);
        var manifest = BuildManifest(types, capabilities, outputs, providers);
        var manifestLiteral = SymbolDisplay.FormatLiteral(manifest, quote: true);
        var manifestBase64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(manifest));
        var base64Literal = SymbolDisplay.FormatLiteral(manifestBase64, quote: true);

        context.AddSource(
            "Feather.AssetManifest.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated/>
                #nullable enable
                [assembly: global::System.Reflection.AssemblyMetadataAttribute("Feather.AssetManifest", {{base64Literal}})]

                namespace Feather.Assets.Generated;

                internal static class FeatherAssetManifest
                {
                    internal const string Json = {{manifestLiteral}};
                }
                """,
                Encoding.UTF8));

        foreach (var type in types)
        {
            EmitCompanion(context, type);
        }
    }

    private static ImmutableArray<AssetContractModel> ValidateContracts(
        SourceProductionContext context,
        ImmutableArray<AssetContractModel> models,
        AssetContractKind expectedKind)
    {
        var result = ImmutableArray.CreateBuilder<AssetContractModel>();
        var ids = new HashSet<string>(StringComparer.Ordinal);
        var typeNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var model in models.OrderBy(static value => value.TypeName, StringComparer.Ordinal))
        {
            var identityValid = TryCanonicalGuid(model.Guid, out var id);
            var valid = true;
            if (model.Kind != expectedKind ||
                !identityValid ||
                !ids.Add(id) ||
                !typeNames.Add(model.TypeName) ||
                !model.IsTopLevel ||
                model.IsGeneric ||
                !model.ImplementsMarker ||
                model.ContractMajor == 0)
            {
                valid = false;
            }

            if (!valid)
            {
                var descriptor = expectedKind == AssetContractKind.Capability
                    ? FeatherDiagnostics.AssetCapabilityContractInvalid
                    : FeatherDiagnostics.AssetOutputContractInvalid;
                context.ReportDiagnostic(Diagnostic.Create(
                    descriptor,
                    model.Location,
                    model.TypeName,
                    model.TypeName,
                    "identity must be canonical and unique; contract must be top-level, non-generic, marker-implementing, and major version must be positive"));
                continue;
            }

            result.Add(model with { Guid = id });
        }

        return result.OrderBy(static value => value.Guid, StringComparer.Ordinal).ToImmutableArray();
    }

    private static ImmutableArray<AssetProviderModel> ValidateProviders(
        SourceProductionContext context,
        ImmutableArray<AssetProviderModel> models)
    {
        var result = ImmutableArray.CreateBuilder<AssetProviderModel>();
        var ids = new HashSet<string>(StringComparer.Ordinal);
        foreach (var model in models.OrderBy(static value => value.TypeName, StringComparer.Ordinal))
        {
            var operation = model.PrimaryOperations.Length == 1 ? model.PrimaryOperations[0] : null;
            if (!TryCanonicalGuid(model.Guid, out var id) ||
                !ids.Add(id) ||
                model.ContractMajor == 0 ||
                operation is null ||
                operation != model.Operation)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.AssetProviderContractInvalid,
                    model.Location,
                    model.TypeName,
                    "provider ID must be canonical and unique, contract major must be positive, and exactly one primary operation interface must match the declared operation"));
                continue;
            }

            result.Add(model with { Guid = id });
        }

        return result.OrderBy(static value => value.Guid, StringComparer.Ordinal).ToImmutableArray();
    }

    private static ImmutableArray<AssetTypeModel> ValidateTypes(
        SourceProductionContext context,
        ImmutableArray<AssetTypeModel> models,
        ImmutableArray<AssetContractModel> capabilities,
        ImmutableArray<AssetContractModel> outputs)
    {
        var capabilityByType = capabilities.ToDictionary(static value => value.TypeName, StringComparer.Ordinal);
        var outputByType = outputs.ToDictionary(static value => value.TypeName, StringComparer.Ordinal);
        var typeIds = new HashSet<string>(StringComparer.Ordinal);
        var validTypes = ImmutableArray.CreateBuilder<AssetTypeModel>();
        foreach (var model in models.OrderBy(static value => value.TypeName, StringComparer.Ordinal))
        {
            if (!TryCanonicalGuid(model.Guid, out var typeId) || !typeIds.Add(typeId))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.AssetTypeIdentityInvalid,
                    model.Location,
                    model.TypeName,
                    model.Guid));
                continue;
            }

            if (!model.IsTopLevel ||
                model.IsGeneric ||
                !model.IsPartial ||
                !model.DerivesAsset ||
                model.ContractMajor == 0 ||
                model.PayloadSchemaVersion is < 1 or > ushort.MaxValue ||
                model.DeclaredAbstract != model.IsAbstract ||
                model.BaseTypeName is not null && !TryCanonicalGuid(model.BaseTypeGuid, out _))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.AssetTypeShapeInvalid,
                    model.Location,
                    model.TypeName,
                    "must be a top-level non-generic partial Asset class with truthful abstract metadata, a positive contract version, a bounded payload schema version, and an annotated nominal base"));
                continue;
            }

            var inputs = ValidateInputs(context, model);
            var typeCapabilities = ValidateCapabilities(context, model, capabilityByType);
            var typeOutputs = ValidateOutputs(context, model, outputByType);
            if (inputs is null || typeCapabilities is null || typeOutputs is null)
            {
                continue;
            }

            validTypes.Add(model with
            {
                Guid = typeId,
                BaseTypeGuid = model.BaseTypeGuid is null ? null : CanonicalGuid(model.BaseTypeGuid),
                Inputs = inputs.Value,
                Capabilities = typeCapabilities.Value,
                Outputs = typeOutputs.Value,
            });
        }

        return validTypes.OrderBy(static value => value.Guid, StringComparer.Ordinal).ToImmutableArray();
    }

    private static ImmutableArray<AssetInputModel>? ValidateInputs(
        SourceProductionContext context,
        AssetTypeModel type)
    {
        var result = ImmutableArray.CreateBuilder<AssetInputModel>();
        var ids = new HashSet<string>(StringComparer.Ordinal);
        var valid = true;
        foreach (var input in type.Inputs)
        {
            if (!TryCanonicalGuid(input.Guid, out var id) || !ids.Add(id))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.AssetInputIdentityInvalid,
                    input.Location,
                    input.SymbolName,
                    type.TypeName,
                    input.Guid));
                valid = false;
                continue;
            }

            var boundsInvalid = input.Minimum is not null && input.Maximum is not null && input.Minimum > input.Maximum ||
                                input.Step is <= 0 ||
                                input.MinimumItems is not null && input.MaximumItems is not null && input.MinimumItems > input.MaximumItems;
            if (input.ValueKind == "UNSUPPORTED" ||
                !input.IsImmutable ||
                input.Role is <= 0 or > 31 ||
                boundsInvalid ||
                input.ValueKind == "TEXT" && input.MaximumLength is null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.AssetInputContractUnsupported,
                    input.Location,
                    input.SymbolName,
                    type.TypeName,
                    "v1 supports immutable bool/int/uint/float/double/string, float vectors, and AssetRef<T>; text is bounded and numeric/list bounds must be coherent"));
                valid = false;
                continue;
            }

            result.Add(input with { Guid = id });
        }

        return valid
            ? result.OrderBy(static value => value.Guid, StringComparer.Ordinal).ToImmutableArray()
            : null;
    }

    private static ImmutableArray<AssetCapabilityUseModel>? ValidateCapabilities(
        SourceProductionContext context,
        AssetTypeModel type,
        IReadOnlyDictionary<string, AssetContractModel> contracts)
    {
        var result = ImmutableArray.CreateBuilder<AssetCapabilityUseModel>();
        var ids = new HashSet<string>(StringComparer.Ordinal);
        var valid = true;
        foreach (var use in type.Capabilities)
        {
            if (!contracts.TryGetValue(use.ContractTypeName, out var contract) ||
                !TryCanonicalGuid(use.Guid, out var id) ||
                id != contract.Guid ||
                !ids.Add(id) ||
                use.MinimumMajor == 0 ||
                use.MinimumMajor != contract.ContractMajor ||
                use.MinimumMinor > contract.ContractMinor)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.AssetCapabilityContractInvalid,
                    use.Location,
                    use.ContractTypeName,
                    type.TypeName,
                    "capability must have a canonical declared contract and a compatible minimum version"));
                valid = false;
                continue;
            }

            result.Add(use with { Guid = id });
        }

        return valid
            ? result.OrderBy(static value => value.Guid, StringComparer.Ordinal).ToImmutableArray()
            : null;
    }

    private static ImmutableArray<AssetOutputModel>? ValidateOutputs(
        SourceProductionContext context,
        AssetTypeModel type,
        IReadOnlyDictionary<string, AssetContractModel> contracts)
    {
        var result = ImmutableArray.CreateBuilder<AssetOutputModel>();
        var ids = new HashSet<string>(StringComparer.Ordinal);
        var symbols = new HashSet<string>(StringComparer.Ordinal);
        var valid = true;
        foreach (var output in type.Outputs)
        {
            if (!contracts.TryGetValue(output.ContractTypeName, out var contract) ||
                !TryCanonicalGuid(output.Guid, out var id) ||
                !TryCanonicalGuid(output.ContractGuid, out var contractId) ||
                contractId != contract.Guid ||
                !ids.Add(id) ||
                string.IsNullOrWhiteSpace(output.Symbol) ||
                !SyntaxFacts.IsValidIdentifier(output.Symbol) ||
                !symbols.Add(output.Symbol) ||
                output.PassDirections is < 0 or > 3)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.AssetOutputContractInvalid,
                    output.Location,
                    output.Symbol,
                    type.TypeName,
                    "slot and contract IDs must be canonical, symbol must be a unique C# identifier, and pass directions must be bounded"));
                valid = false;
                continue;
            }

            result.Add(output with
            {
                Guid = id,
                ContractGuid = contractId,
                ContractMajor = contract.ContractMajor,
                ContractMinor = contract.ContractMinor,
            });
        }

        return valid
            ? result.OrderBy(static value => value.Guid, StringComparer.Ordinal).ToImmutableArray()
            : null;
    }

    private static string BuildManifest(
        ImmutableArray<AssetTypeModel> types,
        ImmutableArray<AssetContractModel> capabilities,
        ImmutableArray<AssetContractModel> outputs,
        ImmutableArray<AssetProviderModel> providers)
    {
        var contentForHash = BuildManifest(types, capabilities, outputs, providers, string.Empty);
        using var sha256 = SHA256.Create();
        var hash = sha256.ComputeHash(Encoding.UTF8.GetBytes(contentForHash));
        var buildId = "sha256:" + BitConverter.ToString(hash).Replace("-", string.Empty).ToLowerInvariant();
        return BuildManifest(types, capabilities, outputs, providers, buildId);
    }

    private static string BuildManifest(
        ImmutableArray<AssetTypeModel> types,
        ImmutableArray<AssetContractModel> capabilities,
        ImmutableArray<AssetContractModel> outputs,
        ImmutableArray<AssetProviderModel> providers,
        string buildId)
    {
        var builder = new StringBuilder();
        builder.AppendLine("{");
        builder.AppendLine("  \"schemaVersion\": 1,");
        JsonProperty(builder, "kind", "Feather.AssetAssemblyManifest", 2, trailingComma: true);
        JsonProperty(builder, "buildId", buildId, 2, trailingComma: true);
        AppendContracts(builder, "capabilityContracts", capabilities, trailingComma: true);
        AppendContracts(builder, "outputContracts", outputs, trailingComma: true);
        AppendProviders(builder, providers, trailingComma: true);
        AppendTypes(builder, types);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendContracts(
        StringBuilder builder,
        string propertyName,
        ImmutableArray<AssetContractModel> contracts,
        bool trailingComma)
    {
        builder.Append("  ").Append(Json(propertyName)).AppendLine(": [");
        for (var index = 0; index < contracts.Length; index++)
        {
            var contract = contracts[index];
            builder.AppendLine("    {");
            JsonProperty(builder, "contractId", contract.Guid, 6, trailingComma: true);
            JsonProperty(builder, "typeName", contract.TypeName, 6, trailingComma: true);
            JsonProperty(builder, "name", contract.Name, 6, trailingComma: true);
            VersionProperty(builder, "contractVersion", contract.ContractMajor, contract.ContractMinor, 6, trailingComma: true);
            SourceProperty(builder, contract.SourcePath, contract.SourceHash, contract.SourceLine, contract.SourceColumn, 6);
            builder.Append("    }").AppendLine(index + 1 < contracts.Length ? "," : string.Empty);
        }
        builder.Append("  ]").AppendLine(trailingComma ? "," : string.Empty);
    }

    private static void AppendProviders(
        StringBuilder builder,
        ImmutableArray<AssetProviderModel> providers,
        bool trailingComma)
    {
        builder.AppendLine("  \"providers\": [");
        for (var index = 0; index < providers.Length; index++)
        {
            var provider = providers[index];
            builder.AppendLine("    {");
            JsonProperty(builder, "providerId", provider.Guid, 6, trailingComma: true);
            JsonProperty(builder, "typeName", provider.TypeName, 6, trailingComma: true);
            JsonProperty(builder, "name", provider.Name, 6, trailingComma: true);
            JsonProperty(builder, "operation", provider.Operation, 6, trailingComma: true);
            VersionProperty(builder, "contractVersion", provider.ContractMajor, provider.ContractMinor, 6, trailingComma: true);
            JsonProperty(builder, "owner", provider.Owner, 6, trailingComma: true);
            JsonProperty(builder, "determinism", provider.Determinism, 6, trailingComma: true);
            StringArrayProperty(builder, "assetTypes", provider.AssetTypeNames, 6, trailingComma: true);
            StringArrayProperty(builder, "outputContracts", provider.OutputContractTypeNames, 6, trailingComma: true);
            SourceProperty(builder, provider.SourcePath, provider.SourceHash, provider.SourceLine, provider.SourceColumn, 6);
            builder.Append("    }").AppendLine(index + 1 < providers.Length ? "," : string.Empty);
        }
        builder.Append("  ]").AppendLine(trailingComma ? "," : string.Empty);
    }

    private static void AppendTypes(StringBuilder builder, ImmutableArray<AssetTypeModel> types)
    {
        var byTypeName = types.ToDictionary(static value => value.TypeName, StringComparer.Ordinal);
        builder.AppendLine("  \"assetTypes\": [");
        for (var index = 0; index < types.Length; index++)
        {
            var type = types[index];
            builder.AppendLine("    {");
            JsonProperty(builder, "typeId", type.Guid, 6, trailingComma: true);
            JsonProperty(builder, "typeName", type.TypeName, 6, trailingComma: true);
            JsonProperty(builder, "displayName", type.DisplayName, 6, trailingComma: true);
            NullableJsonProperty(builder, "description", type.Description, 6, trailingComma: true);
            VersionProperty(builder, "contractVersion", type.ContractMajor, type.ContractMinor, 6, trailingComma: true);
            builder.Append("      \"payloadSchemaVersion\": ").Append(type.PayloadSchemaVersion).AppendLine(",");
            builder.Append("      \"abstract\": ").Append(type.IsAbstract ? "true" : "false").AppendLine(",");
            if (type.BaseTypeGuid is null)
            {
                builder.AppendLine("      \"baseType\": null,");
            }
            else
            {
                builder.AppendLine("      \"baseType\": {");
                JsonProperty(builder, "typeId", type.BaseTypeGuid, 8, trailingComma: true);
                JsonProperty(builder, "typeName", type.BaseTypeName!, 8, trailingComma: false);
                builder.AppendLine("      },");
            }
            StringArrayProperty(builder, "ancestry", Ancestry(type, byTypeName), 6, trailingComma: true);
            SourceProperty(builder, type.SourcePath, type.SourceHash, type.SourceLine, type.SourceColumn, 6, trailingComma: true);
            AppendInputs(builder, type.Inputs);
            AppendCapabilityUses(builder, type.Capabilities);
            AppendOutputs(builder, type.Outputs);
            builder.Append("    }").AppendLine(index + 1 < types.Length ? "," : string.Empty);
        }
        builder.AppendLine("  ]");
    }

    private static void AppendInputs(StringBuilder builder, ImmutableArray<AssetInputModel> inputs)
    {
        builder.AppendLine("      \"inputs\": [");
        for (var index = 0; index < inputs.Length; index++)
        {
            var input = inputs[index];
            builder.AppendLine("        {");
            JsonProperty(builder, "inputId", input.Guid, 10, trailingComma: true);
            JsonProperty(builder, "symbol", input.SymbolName, 10, trailingComma: true);
            JsonProperty(builder, "name", input.Name, 10, trailingComma: true);
            NullableJsonProperty(builder, "group", input.Group, 10, trailingComma: true);
            builder.Append("          \"order\": ").Append(input.Order).AppendLine(",");
            builder.Append("          \"required\": ").Append(input.Required ? "true" : "false").AppendLine(",");
            StringArrayProperty(builder, "role", Roles(input.Role), 10, trailingComma: true);
            JsonProperty(builder, "changeImpact", input.ChangeImpact, 10, trailingComma: true);
            JsonProperty(builder, "valueKind", input.ValueKind, 10, trailingComma: true);
            JsonProperty(builder, "typeName", input.TypeName, 10, trailingComma: true);
            NullableJsonProperty(builder, "referencedAssetType", input.ReferencedAssetTypeName, 10, trailingComma: true);
            NullableNumberProperty(builder, "minimum", input.Minimum, 10, trailingComma: true);
            NullableNumberProperty(builder, "maximum", input.Maximum, 10, trailingComma: true);
            NullableNumberProperty(builder, "step", input.Step, 10, trailingComma: true);
            NullableIntegerProperty(builder, "minimumItems", input.MinimumItems, 10, trailingComma: true);
            NullableIntegerProperty(builder, "maximumItems", input.MaximumItems, 10, trailingComma: true);
            NullableIntegerProperty(builder, "maximumLength", input.MaximumLength, 10, trailingComma: false);
            builder.Append("        }").AppendLine(index + 1 < inputs.Length ? "," : string.Empty);
        }
        builder.AppendLine("      ],");
    }

    private static void AppendCapabilityUses(
        StringBuilder builder,
        ImmutableArray<AssetCapabilityUseModel> capabilities)
    {
        builder.AppendLine("      \"capabilities\": [");
        for (var index = 0; index < capabilities.Length; index++)
        {
            var capability = capabilities[index];
            builder.AppendLine("        {");
            JsonProperty(builder, "capabilityId", capability.Guid!, 10, trailingComma: true);
            JsonProperty(builder, "contractTypeName", capability.ContractTypeName, 10, trailingComma: true);
            VersionProperty(builder, "minimumVersion", capability.MinimumMajor, capability.MinimumMinor, 10, trailingComma: true);
            builder.Append("          \"required\": ").Append(capability.Required ? "true" : "false").AppendLine();
            builder.Append("        }").AppendLine(index + 1 < capabilities.Length ? "," : string.Empty);
        }
        builder.AppendLine("      ],");
    }

    private static void AppendOutputs(StringBuilder builder, ImmutableArray<AssetOutputModel> outputs)
    {
        builder.AppendLine("      \"productSlots\": [");
        for (var index = 0; index < outputs.Length; index++)
        {
            var output = outputs[index];
            builder.AppendLine("        {");
            JsonProperty(builder, "slotId", output.Guid, 10, trailingComma: true);
            JsonProperty(builder, "symbol", output.Symbol, 10, trailingComma: true);
            JsonProperty(builder, "name", output.Name, 10, trailingComma: true);
            JsonProperty(builder, "outputContractId", output.ContractGuid!, 10, trailingComma: true);
            JsonProperty(builder, "outputContractTypeName", output.ContractTypeName, 10, trailingComma: true);
            VersionProperty(builder, "contractVersion", output.ContractMajor, output.ContractMinor, 10, trailingComma: true);
            builder.Append("          \"required\": ").Append(output.Required ? "true" : "false").AppendLine(",");
            builder.Append("          \"graphOutput\": ").Append(output.GraphOutput ? "true" : "false").AppendLine(",");
            StringArrayProperty(builder, "passDirections", Directions(output.PassDirections), 10, trailingComma: false);
            builder.Append("        }").AppendLine(index + 1 < outputs.Length ? "," : string.Empty);
        }
        builder.AppendLine("      ]");
    }

    private static ImmutableArray<string> Ancestry(
        AssetTypeModel type,
        IReadOnlyDictionary<string, AssetTypeModel> byTypeName)
    {
        var result = ImmutableArray.CreateBuilder<string>();
        var current = type;
        var visited = new HashSet<string>(StringComparer.Ordinal);
        while (current.BaseTypeGuid is not null && visited.Add(current.BaseTypeGuid))
        {
            result.Add(current.BaseTypeGuid);
            if (current.BaseTypeName is null || !byTypeName.TryGetValue(current.BaseTypeName, out current!))
            {
                break;
            }
        }
        return result.ToImmutable();
    }

    private static ImmutableArray<string> Roles(long role)
    {
        var result = ImmutableArray.CreateBuilder<string>();
        if ((role & (1L << 0)) != 0) result.Add("EVALUATION");
        if ((role & (1L << 1)) != 0) result.Add("RUNTIME");
        if ((role & (1L << 2)) != 0) result.Add("PREVIEW");
        if ((role & (1L << 3)) != 0) result.Add("EDITOR");
        if ((role & (1L << 4)) != 0) result.Add("PROVENANCE");
        return result.ToImmutable();
    }

    private static ImmutableArray<string> Directions(long directions)
    {
        var result = ImmutableArray.CreateBuilder<string>();
        if ((directions & 1L) != 0) result.Add("INPUT");
        if ((directions & 2L) != 0) result.Add("OUTPUT");
        return result.ToImmutable();
    }

    private static void EmitCompanion(SourceProductionContext context, AssetTypeModel type)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (!string.IsNullOrEmpty(type.Namespace))
        {
            builder.Append("namespace ").Append(type.Namespace).AppendLine(";");
            builder.AppendLine();
        }
        builder.Append("partial class ").Append(EscapeIdentifier(type.Name)).AppendLine();
        builder.AppendLine("{");
        builder.Append("    public ");
        if (type.BaseTypeName is not null)
        {
            builder.Append("new ");
        }
        builder.AppendLine("static class Contract");
        builder.AppendLine("    {");
        builder.Append("        public static global::Feather.Assets.AssetTypeId TypeId { get; } = global::Feather.Assets.AssetTypeId.Parse(")
            .Append(SymbolDisplay.FormatLiteral(type.Guid, quote: true)).AppendLine(");");
        if (!type.Inputs.IsDefaultOrEmpty)
        {
            builder.AppendLine();
            builder.AppendLine("        public static class Inputs");
            builder.AppendLine("        {");
            foreach (var input in type.Inputs)
            {
                builder.Append("            public static global::Feather.Assets.AssetInputId ")
                    .Append(EscapeIdentifier(input.SymbolName))
                    .Append(" { get; } = global::Feather.Assets.AssetInputId.Parse(")
                    .Append(SymbolDisplay.FormatLiteral(input.Guid, quote: true)).AppendLine(");");
            }
            builder.AppendLine("        }");
        }
        if (!type.Outputs.IsDefaultOrEmpty)
        {
            builder.AppendLine();
            builder.AppendLine("        public static class Outputs");
            builder.AppendLine("        {");
            foreach (var output in type.Outputs)
            {
                builder.Append("            public static global::Feather.Assets.AssetProductSlotId ")
                    .Append(output.Symbol)
                    .Append(" { get; } = global::Feather.Assets.AssetProductSlotId.Parse(")
                    .Append(SymbolDisplay.FormatLiteral(output.Guid, quote: true)).AppendLine(");");
            }
            builder.AppendLine("        }");
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");

        var hint = new string(type.TypeName.Select(static character =>
            char.IsLetterOrDigit(character) ? character : '_').ToArray());
        context.AddSource(
            hint + ".Feather.AssetContract.g.cs",
            SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static bool TryCanonicalGuid(string? value, out string canonical)
    {
        if (value is not null &&
            Guid.TryParseExact(value, "D", out var guid) &&
            guid != Guid.Empty &&
            value == guid.ToString("D"))
        {
            canonical = value;
            return true;
        }
        canonical = string.Empty;
        return false;
    }

    private static string CanonicalGuid(string value)
        => TryCanonicalGuid(value, out var canonical)
            ? canonical
            : throw new InvalidOperationException("Validated Asset identity became invalid.");

    private static string EscapeIdentifier(string value)
        => SyntaxFacts.GetKeywordKind(value) != SyntaxKind.None ? "@" + value : value;

    private static void SourceProperty(
        StringBuilder builder,
        string path,
        string documentHash,
        int line,
        int column,
        int indent,
        bool trailingComma = false)
    {
        builder.Append(' ', indent).AppendLine("\"source\": {");
        JsonProperty(builder, "path", path, indent + 2, trailingComma: true);
        JsonProperty(builder, "documentHash", documentHash, indent + 2, trailingComma: true);
        builder.Append(' ', indent + 2).Append("\"line0\": ").Append(line).AppendLine(",");
        builder.Append(' ', indent + 2).Append("\"column0\": ").Append(column).AppendLine();
        builder.Append(' ', indent).Append('}').AppendLine(trailingComma ? "," : string.Empty);
    }

    private static void VersionProperty(
        StringBuilder builder,
        string name,
        ushort major,
        ushort minor,
        int indent,
        bool trailingComma)
    {
        builder.Append(' ', indent).Append(Json(name)).AppendLine(": {");
        builder.Append(' ', indent + 2).Append("\"major\": ").Append(major).AppendLine(",");
        builder.Append(' ', indent + 2).Append("\"minor\": ").Append(minor).AppendLine();
        builder.Append(' ', indent).Append('}').AppendLine(trailingComma ? "," : string.Empty);
    }

    private static void JsonProperty(
        StringBuilder builder,
        string name,
        string value,
        int indent,
        bool trailingComma)
        => builder.Append(' ', indent).Append(Json(name)).Append(": ").Append(Json(value))
            .AppendLine(trailingComma ? "," : string.Empty);

    private static void NullableJsonProperty(
        StringBuilder builder,
        string name,
        string? value,
        int indent,
        bool trailingComma)
        => builder.Append(' ', indent).Append(Json(name)).Append(": ")
            .Append(value is null ? "null" : Json(value)).AppendLine(trailingComma ? "," : string.Empty);

    private static void NullableNumberProperty(
        StringBuilder builder,
        string name,
        double? value,
        int indent,
        bool trailingComma)
        => builder.Append(' ', indent).Append(Json(name)).Append(": ")
            .Append(value?.ToString("R", CultureInfo.InvariantCulture) ?? "null")
            .AppendLine(trailingComma ? "," : string.Empty);

    private static void NullableIntegerProperty(
        StringBuilder builder,
        string name,
        int? value,
        int indent,
        bool trailingComma)
        => builder.Append(' ', indent).Append(Json(name)).Append(": ")
            .Append(value?.ToString(CultureInfo.InvariantCulture) ?? "null")
            .AppendLine(trailingComma ? "," : string.Empty);

    private static void StringArrayProperty(
        StringBuilder builder,
        string name,
        IEnumerable<string> values,
        int indent,
        bool trailingComma)
    {
        builder.Append(' ', indent).Append(Json(name)).Append(": [")
            .Append(string.Join(", ", values.Select(Json))).Append(']')
            .AppendLine(trailingComma ? "," : string.Empty);
    }

    private static string Json(string value)
    {
        var builder = new StringBuilder(value.Length + 2).Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '"': builder.Append("\\\""); break;
                case '\\': builder.Append("\\\\"); break;
                case '\b': builder.Append("\\b"); break;
                case '\f': builder.Append("\\f"); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                default:
                    if (character < ' ')
                    {
                        builder.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(character);
                    }
                    break;
            }
        }
        return builder.Append('"').ToString();
    }
}
