using System.Collections.Immutable;
using System.Security.Cryptography;
using System.Text;
using Feather.Generators.Diagnostics;
using Feather.Generators.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Feather.Generators;

internal static class DataManifestWriter
{
    public static void Emit(SourceProductionContext context, ImmutableArray<DataTypeModel> models)
    {
        if (models.IsDefaultOrEmpty)
        {
            return;
        }

        var valid = Validate(context, models);
        if (valid.IsDefaultOrEmpty)
        {
            return;
        }

        string manifest = BuildManifest(valid);
        string manifestBase64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(manifest));
        string manifestLiteral = SymbolDisplay.FormatLiteral(manifest, quote: true);
        string base64Literal = SymbolDisplay.FormatLiteral(manifestBase64, quote: true);
        context.AddSource(
            "Feather.DataManifest.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated/>
                #nullable enable
                [assembly: global::System.Reflection.AssemblyMetadataAttribute("Feather.DataManifest", {{base64Literal}})]

                namespace Feather.RenderGraph.Generated;

                internal static class FeatherDataManifest
                {
                    internal const string Json = {{manifestLiteral}};
                }
                """,
                Encoding.UTF8));
    }

    private static ImmutableArray<DataTypeModel> Validate(
        SourceProductionContext context,
        ImmutableArray<DataTypeModel> models)
    {
        var result = ImmutableArray.CreateBuilder<DataTypeModel>();
        var typeIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var model in models.OrderBy(static value => value.TypeName, StringComparer.Ordinal))
        {
            if (!TryCanonicalGuid(model.Guid, out var typeId) ||
                !typeIds.Add(typeId) ||
                !model.IsTopLevel ||
                model.IsGeneric ||
                model.ContractMajor == 0 ||
                model.Resources.IsDefaultOrEmpty)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.DataTypeContractInvalid,
                    model.Location,
                    model.TypeName,
                    "identity must be canonical and unique; declaration must be top-level, non-generic, versioned, and contain at least one resource"));
                continue;
            }

            var resourceIds = new HashSet<string>(StringComparer.Ordinal);
            var resources = ImmutableArray.CreateBuilder<DataResourceModel>();
            var resourceValid = true;
            foreach (var resource in model.Resources)
            {
                if (!TryCanonicalGuid(resource.Guid, out var resourceId) ||
                    !resourceIds.Add(resourceId) ||
                    resource.Kind == "UNSUPPORTED" ||
                    resource.Access is < 1 or > 3 ||
                    resource.ElementSizeBytes <= 0 ||
                    resource.ElementAlignmentBytes <= 0 ||
                    resource.MaximumBytes is < 1 or > (1L << 40) ||
                    resource.ElementCount is < 0 or > 1_073_741_824 ||
                    resource.Width is < 0 or > 16_384 ||
                    resource.Height is < 0 or > 16_384 ||
                    resource.Depth is < 0 or > 16_384 ||
                    resource.Format is { Length: > 128 } ||
                    resource.Update == 0 && (resource.Access & 2) != 0 ||
                    resource.Lifetime == 3 && resource.Update == 3 ||
                    resource.Frames == 1 &&
                    (resource.Kind != "TEXTURE_2D" || resource.Access != 3 || resource.Update != 3) ||
                    !ShapeIsValid(resource))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        FeatherDiagnostics.DataResourceContractInvalid,
                        resource.Location,
                        resource.Symbol,
                        model.TypeName,
                        "use one supported typed resource marker, canonical identity, valid std430 element, explicit byte budget, coherent shape/access/update/lifetime, and valid frame policy"));
                    resourceValid = false;
                    continue;
                }
                resources.Add(resource with { Guid = resourceId });
            }

            if (resourceValid)
            {
                result.Add(model with
                {
                    Guid = typeId,
                    Resources = resources
                        .OrderBy(static value => value.Guid, StringComparer.Ordinal)
                        .ToImmutableArray(),
                });
            }
        }
        return result.OrderBy(static value => value.Guid, StringComparer.Ordinal).ToImmutableArray();
    }

    private static bool ShapeIsValid(DataResourceModel resource)
        => resource.Kind switch
        {
            "BUFFER" => resource.ElementCount > 0 &&
                        resource.MaximumBytes >= resource.ElementCount *
                            GpuStructLayoutRules.Align(
                                resource.ElementSizeBytes,
                                resource.ElementAlignmentBytes),
            "TEXTURE_1D" => resource.Width > 0,
            "TEXTURE_2D" => resource.Width > 0 && resource.Height > 0,
            "TEXTURE_3D" or "PROBE_VOLUME" or "RADIANCE_CASCADE" =>
                resource.Width > 0 && resource.Height > 0 && resource.Depth > 0,
            "CUSTOM" => true,
            _ => false,
        };

    private static string BuildManifest(ImmutableArray<DataTypeModel> types)
    {
        var builder = new StringBuilder();
        builder.AppendLine("{");
        builder.AppendLine("  \"schemaVersion\": 1,");
        builder.AppendLine("  \"kind\": \"Feather.DataAssemblyManifest\",");
        builder.AppendLine("  \"types\": [");
        for (int index = 0; index < types.Length; index++)
        {
            AppendType(builder, types[index], index + 1 < types.Length);
        }
        builder.AppendLine("  ]");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendType(StringBuilder builder, DataTypeModel type, bool trailingComma)
    {
        string layoutIdentity = string.Join(
            "\n",
            type.Resources.Select(static resource =>
                string.Join("|",
                    resource.Guid,
                    resource.Kind,
                    resource.Access,
                    resource.ElementType,
                    resource.ElementLayoutIdentity,
                    resource.Creation,
                    resource.Update,
                    resource.Lifetime,
                    resource.Frames,
                    resource.MaximumBytes,
                    resource.ElementCount,
                    resource.Width,
                    resource.Height,
                    resource.Depth,
                    resource.Format ?? string.Empty)));
        string layoutHash = Hash(layoutIdentity);
        string documentWithoutManifestHash = BuildTypeDocument(type, string.Empty, layoutHash);
        string manifestHash = Hash(documentWithoutManifestHash);
        string document = BuildTypeDocument(type, manifestHash, layoutHash)
            .Replace("\n", "\n      ");

        builder.AppendLine("    {");
        JsonProperty(builder, "sourcePath", type.SourcePath, 6, trailingComma: true);
        JsonProperty(builder, "sourceHash", type.SourceHash, 6, trailingComma: true);
        builder.AppendLine("      \"sourceLine\": " + type.SourceLine + ",");
        builder.AppendLine("      \"sourceColumn\": " + type.SourceColumn + ",");
        builder.AppendLine("      \"document\": " + document.TrimStart());
        builder.Append("    }");
        builder.AppendLine(trailingComma ? "," : string.Empty);
    }

    private static string BuildTypeDocument(DataTypeModel type, string manifestHash, string layoutHash)
    {
        var builder = new StringBuilder();
        builder.AppendLine("{");
        builder.AppendLine("  \"schemaVersion\": 1,");
        JsonProperty(builder, "typeId", type.Guid, 2, trailingComma: true);
        JsonProperty(builder, "manifestHash", manifestHash, 2, trailingComma: true);
        builder.AppendLine("  \"contractVersion\": { \"major\": " + type.ContractMajor + ", \"minor\": " + type.ContractMinor + " },");
        JsonProperty(builder, "displayName", type.DisplayName, 2, trailingComma: true);
        JsonProperty(builder, "layoutAbiHash", layoutHash, 2, trailingComma: true);
        builder.AppendLine("  \"structureSizeBytes\": 0,");
        builder.AppendLine("  \"structureAlignmentBytes\": 1,");
        builder.AppendLine("  \"fields\": [],");
        builder.AppendLine("  \"resources\": [");
        for (int index = 0; index < type.Resources.Length; index++)
        {
            AppendResource(builder, type.Resources[index], index + 1 < type.Resources.Length);
        }
        builder.AppendLine("  ]");
        builder.Append('}');
        return builder.ToString();
    }

    private static void AppendResource(StringBuilder builder, DataResourceModel resource, bool trailingComma)
    {
        int elementStrideBytes = GpuStructLayoutRules.Align(
            resource.ElementSizeBytes,
            resource.ElementAlignmentBytes);
        string elementLayoutAbiHash = Hash(resource.ElementLayoutIdentity);
        builder.AppendLine("    {");
        JsonProperty(builder, "resourceId", resource.Guid, 6, trailingComma: true);
        JsonProperty(builder, "name", resource.Name, 6, trailingComma: true);
        JsonProperty(builder, "kind", resource.Kind, 6, trailingComma: true);
        builder.Append("      \"access\": [\"READ\"");
        if (resource.Access == 2)
        {
            builder.Length -= "\"READ\"".Length;
            builder.Append("\"WRITE\"");
        }
        else if (resource.Access == 3)
        {
            builder.Append(", \"WRITE\"");
        }
        builder.AppendLine("],");
        JsonProperty(builder, "elementType", resource.ElementType, 6, trailingComma: true);
        JsonProperty(builder, "elementLayoutAbiHash", elementLayoutAbiHash, 6, trailingComma: true);
        builder.AppendLine("      \"elementStrideBytes\": " + elementStrideBytes + ",");
        builder.AppendLine("      \"elementAlignmentBytes\": " + resource.ElementAlignmentBytes + ",");
        JsonProperty(builder, "creationPhase", resource.Creation == 0 ? "BEFORE_GRAPH" : "FIRST_USE", 6, trailingComma: true);
        JsonProperty(builder, "updateMode", resource.Update switch
        {
            0 => "IMMUTABLE",
            1 => "ON_DEMAND",
            2 => "PASS_MUTATED",
            _ => "PER_FRAME",
        }, 6, trailingComma: true);
        JsonProperty(builder, "lifetime", resource.Lifetime switch
        {
            0 => "VIEW",
            1 => "GRAPH",
            2 => "WORKSPACE",
            _ => "PERSISTENT",
        }, 6, trailingComma: true);
        builder.AppendLine("      \"maximumBytes\": " + resource.MaximumBytes + ",");
        if (resource.ElementCount > 0) builder.AppendLine("      \"elementCount\": " + resource.ElementCount + ",");
        if (resource.Width > 0) builder.AppendLine("      \"width\": " + resource.Width + ",");
        if (resource.Height > 0) builder.AppendLine("      \"height\": " + resource.Height + ",");
        if (resource.Depth > 0) builder.AppendLine("      \"depth\": " + resource.Depth + ",");
        if (resource.Format is not null) JsonProperty(builder, "format", resource.Format, 6, trailingComma: true);
        JsonProperty(builder, "framePolicy", resource.Frames == 0 ? "SINGLE" : "DOUBLE_BUFFERED", 6, trailingComma: false);
        builder.Append("    }");
        builder.AppendLine(trailingComma ? "," : string.Empty);
    }

    private static string Hash(string value)
    {
        using var sha256 = SHA256.Create();
        byte[] hash = sha256.ComputeHash(Encoding.UTF8.GetBytes(value));
        return "sha256:" + BitConverter.ToString(hash).Replace("-", string.Empty).ToLowerInvariant();
    }

    private static bool TryCanonicalGuid(string value, out string canonical)
    {
        canonical = string.Empty;
        if (!Guid.TryParseExact(value, "D", out var guid)) return false;
        canonical = guid.ToString("D");
        return string.Equals(value, canonical, StringComparison.Ordinal);
    }

    private static void JsonProperty(
        StringBuilder builder,
        string name,
        string value,
        int indent,
        bool trailingComma)
    {
        builder.Append(' ', indent)
            .Append('"').Append(Escape(name)).Append("\": ")
            .Append('"').Append(Escape(value)).Append('"');
        if (trailingComma) builder.Append(',');
        builder.AppendLine();
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"")
            .Replace("\r", "\\r").Replace("\n", "\\n");
}
