using System.Collections.Immutable;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Feather.Generators.Diagnostics;
using Feather.Generators.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Feather.Generators;

internal sealed record PassManifestOptions(
    string? ProjectDirectory,
    string AssemblyPath,
    string FeirDirectory)
{
    public static PassManifestOptions Create(AnalyzerConfigOptions options)
    {
        options.TryGetValue("build_property.ProjectDir", out var projectDirectory);
        options.TryGetValue("build_property.FeatherAssemblyPath", out var assemblyPath);
        options.TryGetValue("build_property.FeatherFeirDirectory", out var feirDirectory);

        assemblyPath = string.IsNullOrWhiteSpace(assemblyPath)
            ? "__FEATHER_ASSEMBLY_PATH__"
            : assemblyPath;
        feirDirectory = string.IsNullOrWhiteSpace(feirDirectory)
            ? "__FEATHER_FEIR_DIRECTORY__"
            : feirDirectory;

        return new PassManifestOptions(
            NullIfWhiteSpace(projectDirectory),
            NormalizePath(assemblyPath!),
            NormalizePath(feirDirectory!));
    }

    private static string? NullIfWhiteSpace(string? value)
        => string.IsNullOrWhiteSpace(value) ? null : value;

    private static string NormalizePath(string value)
        => value.Replace('\\', '/');
}

internal static class PassManifestWriter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<PassModel> models,
        PassManifestOptions options)
    {
        if (models.IsDefaultOrEmpty)
        {
            return;
        }

        var validPasses = Validate(context, models)
            .OrderBy(static pass => pass.Guid, StringComparer.Ordinal)
            .ToImmutableArray();
        var manifest = BuildManifest(validPasses, options);
        var manifestLiteral = Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
            manifest,
            quote: true);
        var manifestBase64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(manifest));
        var base64Literal = Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
            manifestBase64,
            quote: true);

        context.AddSource(
            "Feather.PassManifest.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated/>
                #nullable enable
                [assembly: global::System.Reflection.AssemblyMetadataAttribute("Feather.PassManifest", {{base64Literal}})]

                namespace Feather.RenderGraph.Generated;

                internal static class FeatherPassManifest
                {
                    internal const string Json = {{manifestLiteral}};
                }
                """,
                Encoding.UTF8));

    }

    private static IEnumerable<PassModel> Validate(
        SourceProductionContext context,
        ImmutableArray<PassModel> models)
    {
        var passGuids = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var model in models)
        {
            if (!TryNormalizeGuid(context, model.Guid, model.TypeName, model.Location, out var passGuid))
            {
                continue;
            }
            if (!passGuids.Add(passGuid))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.RenderGraphGuidDuplicate,
                    model.Location,
                    passGuid,
                    "the render graph"));
                continue;
            }
            if (!model.ImplementsRenderPass)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.RenderPassContractInvalid,
                    model.Location,
                    model.TypeName));
                continue;
            }

            var memberGuids = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var valid = true;
            var inputs = NormalizeSockets(context, model, model.Inputs, memberGuids, ref valid);
            var outputs = NormalizeSockets(context, model, model.Outputs, memberGuids, ref valid);
            var parameters = ImmutableArray.CreateBuilder<PassParameterModel>();
            foreach (var parameter in model.Parameters)
            {
                if (!TryNormalizeGuid(
                        context,
                        parameter.Guid,
                        $"{model.TypeName}.{parameter.Name}",
                        parameter.Location,
                        out var parameterGuid))
                {
                    valid = false;
                    continue;
                }
                if (!memberGuids.Add(parameterGuid))
                {
                    ReportDuplicate(context, parameterGuid, model, parameter.Location);
                    valid = false;
                    continue;
                }
                PassEnumModel? enumContract = null;
                if (parameter.Enum is not null &&
                    !TryNormalizeEnum(context, parameter, parameter.Enum, out enumContract))
                {
                    valid = false;
                    continue;
                }
                parameters.Add(parameter with
                {
                    Guid = parameterGuid,
                    TypeIdentity = enumContract?.TypeGuid,
                    Enum = enumContract,
                });
            }

            if (valid)
            {
                yield return model with
                {
                    Guid = passGuid,
                    Inputs = inputs,
                    Outputs = outputs,
                    Parameters = parameters.ToImmutable()
                };
            }
        }
    }

    private static bool TryNormalizeEnum(
        SourceProductionContext context,
        PassParameterModel parameter,
        PassEnumModel source,
        out PassEnumModel? normalized)
    {
        normalized = null;
        if (string.IsNullOrWhiteSpace(source.TypeGuid) ||
            source.Members.Any(static member => string.IsNullOrWhiteSpace(member.Guid)))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                FeatherDiagnostics.EnumIdentityMissing,
                parameter.Location,
                source.TypeName));
            return false;
        }
        if (source.UnderlyingScalar is "I64" or "U64" or "UNSUPPORTED")
        {
            context.ReportDiagnostic(Diagnostic.Create(
                FeatherDiagnostics.EnumUnderlyingUnsupported,
                parameter.Location,
                source.TypeName,
                source.UnderlyingScalar));
            return false;
        }
        if (!TryNormalizeGuid(
                context,
                source.TypeGuid,
                source.TypeName,
                source.Location,
                out var typeGuid))
        {
            return false;
        }

        var memberGuids = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { typeGuid };
        var members = ImmutableArray.CreateBuilder<PassEnumMemberModel>();
        foreach (var member in source.Members)
        {
            if (!TryNormalizeGuid(
                    context,
                    member.Guid,
                    source.TypeName + "." + member.SymbolName,
                    member.Location,
                    out var memberGuid))
            {
                return false;
            }
            if (!memberGuids.Add(memberGuid))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.EnumContractInvalid,
                    member.Location,
                    source.TypeName,
                    "duplicate enum type/member GUID " + memberGuid));
                return false;
            }

            string? replacementGuid = null;
            if (!string.IsNullOrWhiteSpace(member.ReplacementMemberGuid))
            {
                if (!TryNormalizeGuid(
                        context,
                        member.ReplacementMemberGuid!,
                        source.TypeName + "." + member.SymbolName + " replacement",
                        member.Location,
                        out replacementGuid))
                {
                    return false;
                }
            }
            members.Add(member with
            {
                Guid = memberGuid,
                ReplacementMemberGuid = replacementGuid,
            });
        }

        var normalizedMembers = members.ToImmutable();
        var knownMemberGuids = new HashSet<string>(
            normalizedMembers.Select(static member => member.Guid),
            StringComparer.OrdinalIgnoreCase);
        var missingReplacement = normalizedMembers.FirstOrDefault(member =>
            member.ReplacementMemberGuid is not null &&
            !knownMemberGuids.Contains(member.ReplacementMemberGuid));
        if (missingReplacement is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                FeatherDiagnostics.EnumContractInvalid,
                missingReplacement.Location,
                source.TypeName,
                "replacement member GUID is not declared: " + missingReplacement.ReplacementMemberGuid));
            return false;
        }
        if (!source.IsFlags && normalizedMembers.GroupBy(static member => member.NumericValue)
                .Any(static group => group.Count() > 1))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                FeatherDiagnostics.EnumContractInvalid,
                source.Location,
                source.TypeName,
                "normal enum numeric values must be unique"));
            return false;
        }

        long allowedMask = 0;
        foreach (var member in normalizedMembers) allowedMask |= member.NumericValue;
        if (!source.IsFlags &&
            !source.AllowUnknownNumeric &&
            normalizedMembers.All(member => member.NumericValue != source.DefaultRawValue))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                FeatherDiagnostics.EnumContractInvalid,
                parameter.Location,
                source.TypeName,
                "default value is not a declared member"));
            return false;
        }
        if (source.IsFlags &&
            !source.AllowUnknownBits &&
            HasUnknownBits(source.DefaultRawValue, allowedMask, source.UnderlyingScalar))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                FeatherDiagnostics.EnumContractInvalid,
                parameter.Location,
                source.TypeName,
                "default flags value contains bits outside allowedMask"));
            return false;
        }

        normalized = source with
        {
            TypeGuid = typeGuid,
            AllowedMask = allowedMask,
            Members = normalizedMembers,
        };
        return true;
    }

    private static bool HasUnknownBits(long rawValue, long allowedMask, string scalarKind)
    {
        ulong widthMask = scalarKind switch
        {
            "I8" or "U8" => byte.MaxValue,
            "I16" or "U16" => ushort.MaxValue,
            _ => uint.MaxValue,
        };
        ulong raw = unchecked((ulong)rawValue) & widthMask;
        ulong allowed = unchecked((ulong)allowedMask) & widthMask;
        return (raw & ~allowed & widthMask) != 0;
    }

    private static ImmutableArray<PassSocketModel> NormalizeSockets(
        SourceProductionContext context,
        PassModel model,
        ImmutableArray<PassSocketModel> sockets,
        HashSet<string> memberGuids,
        ref bool valid)
    {
        var result = ImmutableArray.CreateBuilder<PassSocketModel>();
        foreach (var socket in sockets)
        {
            if (!TryNormalizeGuid(
                    context,
                    socket.Guid,
                    $"{model.TypeName}.{socket.Name}",
                    socket.Location,
                    out var socketGuid))
            {
                valid = false;
                continue;
            }
            if (!memberGuids.Add(socketGuid))
            {
                ReportDuplicate(context, socketGuid, model, socket.Location);
                valid = false;
                continue;
            }
            var contract = NormalizeSocketContract(context, model, socket, ref valid);
            if (contract is not null)
            {
                result.Add(socket with { Guid = socketGuid, Contract = contract });
            }
        }
        return result.ToImmutable();
    }

    private static PassSocketContractModel? NormalizeSocketContract(
        SourceProductionContext context,
        PassModel model,
        PassSocketModel socket,
        ref bool valid)
    {
        if (socket.Contract.Kind == "GPU_RESOURCE")
        {
            return socket.Contract;
        }

        if (!TryCanonicalAssetGuid(socket.Contract.RequiredAssetTypeId, out var typeId) ||
            socket.Contract.RequiredAssetTypeMajor == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                FeatherDiagnostics.AssetTypeShapeInvalid,
                socket.Location,
                model.TypeName + "." + socket.Name,
                "Asset pass socket requires an annotated Asset Type with a canonical identity and positive contract version"));
            valid = false;
            return null;
        }

        var capabilities = ImmutableArray.CreateBuilder<PassSocketCapabilityModel>();
        var capabilityIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var capability in socket.Contract.RequiredCapabilities)
        {
            if (!TryCanonicalAssetGuid(capability.CapabilityId, out var capabilityId) ||
                !capabilityIds.Add(capabilityId) ||
                capability.MinimumMajor == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.AssetCapabilityContractInvalid,
                    socket.Location,
                    capability.CapabilityId,
                    model.TypeName + "." + socket.Name,
                    "required capability identity/version must be canonical, positive, and unique"));
                valid = false;
                return null;
            }
            capabilities.Add(capability with { CapabilityId = capabilityId });
        }

        if (socket.Contract.Kind == "ASSET_REFERENCE")
        {
            return socket.Contract with
            {
                RequiredAssetTypeId = typeId,
                RequiredCapabilities = capabilities.ToImmutable(),
            };
        }

        if (socket.Contract.Kind != "ASSET_PRODUCT" ||
            !TryCanonicalAssetGuid(socket.Contract.ProductSlotId, out var slotId) ||
            !TryCanonicalAssetGuid(socket.Contract.OutputContractId, out var outputContractId) ||
            socket.Contract.OutputContractMajor == 0 ||
            !socket.Contract.AdapterRequired)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                FeatherDiagnostics.AssetOutputContractInvalid,
                socket.Location,
                socket.Name,
                model.TypeName,
                "prepared product socket requires a matching [AssetProductBinding], stable slot, output contract/version, and runtime adapter boundary"));
            valid = false;
            return null;
        }

        return socket.Contract with
        {
            RequiredAssetTypeId = typeId,
            RequiredCapabilities = capabilities.ToImmutable(),
            ProductSlotId = slotId,
            OutputContractId = outputContractId,
        };
    }

    private static bool TryCanonicalAssetGuid(string? value, out string canonical)
    {
        if (value is not null &&
            Guid.TryParseExact(value, "D", out var guid) &&
            guid != Guid.Empty &&
            value == guid.ToString("D"))
        {
            canonical = value;
            return true;
        }

        canonical = string.Empty;
        return false;
    }

    private static bool TryNormalizeGuid(
        SourceProductionContext context,
        string value,
        string owner,
        Location location,
        out string normalized)
    {
        if (Guid.TryParseExact(value, "D", out var guid))
        {
            normalized = guid.ToString("D");
            return true;
        }

        context.ReportDiagnostic(Diagnostic.Create(
            FeatherDiagnostics.RenderGraphGuidInvalid,
            location,
            value,
            owner));
        normalized = string.Empty;
        return false;
    }

    private static void ReportDuplicate(
        SourceProductionContext context,
        string guid,
        PassModel model,
        Location location)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            FeatherDiagnostics.RenderGraphGuidDuplicate,
            location,
            guid,
            model.TypeName));
    }

    private static string BuildManifest(
        ImmutableArray<PassModel> passes,
        PassManifestOptions options)
    {
        var contentForHash = BuildManifest(passes, options, buildId: string.Empty);
        using var sha256 = SHA256.Create();
        var hash = sha256.ComputeHash(Encoding.UTF8.GetBytes(contentForHash));
        var buildId = "sha256:" + BitConverter.ToString(hash).Replace("-", string.Empty).ToLowerInvariant();
        return BuildManifest(passes, options, buildId);
    }

    private static string BuildManifest(
        ImmutableArray<PassModel> passes,
        PassManifestOptions options,
        string buildId)
    {
        var builder = new StringBuilder();
        builder.AppendLine("{");
        builder.AppendLine("  \"schemaVersion\": 2,");
        AppendJsonString(builder, "buildId", buildId, 2, trailingComma: true);
        AppendJsonString(builder, "assemblyPath", options.AssemblyPath, 2, trailingComma: true);
        AppendJsonString(builder, "feirDirectory", options.FeirDirectory, 2, trailingComma: true);
        builder.AppendLine("  \"passes\": [");
        for (var index = 0; index < passes.Length; index++)
        {
            AppendPass(builder, passes[index], options, index + 1 < passes.Length);
        }
        builder.AppendLine("  ]");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendPass(
        StringBuilder builder,
        PassModel pass,
        PassManifestOptions options,
        bool trailingComma)
    {
        builder.AppendLine("    {");
        AppendJsonString(builder, "passGuid", pass.Guid, 6, trailingComma: true);
        AppendJsonString(builder, "typeName", pass.TypeName, 6, trailingComma: true);
        AppendJsonString(builder, "displayName", pass.DisplayName, 6, trailingComma: true);
        AppendJsonString(builder, "category", pass.Category, 6, trailingComma: true);
        builder.Append("      \"version\": ").Append(pass.Version).AppendLine(",");
        AppendJsonString(builder, "assemblyPath", options.AssemblyPath, 6, trailingComma: true);
        AppendJsonString(
            builder,
            "feirPath",
            options.FeirDirectory.TrimEnd('/') + "/" + pass.Guid + ".feir",
            6,
            trailingComma: true);
        builder.AppendLine("      \"source\": {");
        AppendJsonString(
            builder,
            "path",
            RelativeSourcePath(pass.SourcePath, options.ProjectDirectory),
            8,
            trailingComma: true);
        builder.Append("        \"line0\": ").Append(pass.SourceLine).AppendLine(",");
        builder.Append("        \"column0\": ").Append(pass.SourceColumn).AppendLine();
        builder.AppendLine("      },");
        AppendSockets(builder, "inputs", pass.Inputs, trailingComma: true);
        AppendSockets(builder, "outputs", pass.Outputs, trailingComma: true);
        AppendParameters(builder, pass.Parameters);
        builder.Append("    }");
        builder.AppendLine(trailingComma ? "," : string.Empty);
    }

    private static void AppendSockets(
        StringBuilder builder,
        string name,
        ImmutableArray<PassSocketModel> sockets,
        bool trailingComma)
    {
        builder.Append("      ").Append(JsonString(name)).AppendLine(": [");
        for (var index = 0; index < sockets.Length; index++)
        {
            var socket = sockets[index];
            builder.AppendLine("        {");
            AppendJsonString(builder, "socketGuid", socket.Guid, 10, trailingComma: true);
            AppendJsonString(builder, "name", socket.Name, 10, trailingComma: true);
            AppendJsonString(builder, "resourceKind", socket.ResourceKind, 10, trailingComma: true);
            if (socket.ElementType is not null)
            {
                AppendJsonString(builder, "elementType", socket.ElementType, 10, trailingComma: true);
            }
            AppendJsonString(builder, "format", socket.Format, 10, trailingComma: true);
            AppendJsonString(builder, "access", socket.Access, 10, trailingComma: true);
            AppendJsonString(
                builder,
                "contractKind",
                socket.Contract.Kind,
                10,
                trailingComma: socket.Contract.Kind != "GPU_RESOURCE");
            if (socket.Contract.Kind != "GPU_RESOURCE")
            {
                AppendAssetSocketContract(builder, socket.Contract);
            }
            builder.Append("        }").AppendLine(index + 1 < sockets.Length ? "," : string.Empty);
        }
        builder.Append("      ]").AppendLine(trailingComma ? "," : string.Empty);
    }

    private static void AppendAssetSocketContract(
        StringBuilder builder,
        PassSocketContractModel contract)
    {
        builder.AppendLine("          \"assetContract\": {");
        AppendJsonString(builder, "requiredTypeId", contract.RequiredAssetTypeId!, 12, trailingComma: true);
        builder.AppendLine("            \"requiredTypeVersion\": {");
        builder.Append("              \"major\": ").Append(contract.RequiredAssetTypeMajor).AppendLine(",");
        builder.Append("              \"minor\": ").Append(contract.RequiredAssetTypeMinor).AppendLine();
        builder.AppendLine("            },");
        builder.AppendLine("            \"requiredCapabilities\": [");
        for (var index = 0; index < contract.RequiredCapabilities.Length; index++)
        {
            var capability = contract.RequiredCapabilities[index];
            builder.AppendLine("              {");
            AppendJsonString(builder, "capabilityId", capability.CapabilityId, 16, trailingComma: true);
            builder.AppendLine("                \"minimumVersion\": {");
            builder.Append("                  \"major\": ").Append(capability.MinimumMajor).AppendLine(",");
            builder.Append("                  \"minor\": ").Append(capability.MinimumMinor).AppendLine();
            builder.AppendLine("                },");
            builder.Append("                \"required\": ")
                .Append(capability.Required ? "true" : "false").AppendLine();
            builder.Append("              }").AppendLine(
                index + 1 < contract.RequiredCapabilities.Length ? "," : string.Empty);
        }
        builder.AppendLine("            ],");
        builder.Append("            \"productSlotId\": ")
            .Append(JsonNullableString(contract.ProductSlotId)).AppendLine(",");
        builder.Append("            \"outputContractId\": ")
            .Append(JsonNullableString(contract.OutputContractId)).AppendLine(",");
        if (contract.OutputContractId is null)
        {
            builder.AppendLine("            \"outputContractVersion\": null,");
        }
        else
        {
            builder.AppendLine("            \"outputContractVersion\": {");
            builder.Append("              \"major\": ").Append(contract.OutputContractMajor).AppendLine(",");
            builder.Append("              \"minor\": ").Append(contract.OutputContractMinor).AppendLine();
            builder.AppendLine("            },");
        }
        builder.Append("            \"adapterRequired\": ")
            .Append(contract.AdapterRequired ? "true" : "false").AppendLine();
        builder.AppendLine("          }");
    }

    private static void AppendParameters(
        StringBuilder builder,
        ImmutableArray<PassParameterModel> parameters)
    {
        builder.AppendLine("      \"parameters\": [");
        for (var index = 0; index < parameters.Length; index++)
        {
            var parameter = parameters[index];
            builder.AppendLine("        {");
            AppendJsonString(builder, "parameterGuid", parameter.Guid, 10, trailingComma: true);
            AppendJsonString(builder, "name", parameter.Name, 10, trailingComma: true);
            AppendJsonString(builder, "type", parameter.Type, 10, trailingComma: true);
            AppendJsonString(builder, "logicalType", parameter.LogicalType, 10, trailingComma: true);
            builder.Append("          \"typeIdentity\": ")
                .Append(JsonNullableString(parameter.TypeIdentity))
                .AppendLine(",");
            builder.Append("          \"defaultValue\": ")
                .Append(parameter.Enum is null
                    ? parameter.DefaultValueJson ?? "null"
                    : EnumDefaultJson(parameter.Enum))
                .AppendLine(",");
            builder.AppendLine("          \"constraints\": {");
            builder.Append("            \"min\": ").Append(JsonNumber(parameter.Min)).AppendLine(",");
            builder.Append("            \"max\": ").Append(JsonNumber(parameter.Max)).AppendLine(",");
            builder.Append("            \"step\": ").Append(JsonNumber(parameter.Step)).AppendLine(",");
            builder.Append("            \"unit\": ").Append(JsonNullableString(parameter.Unit)).AppendLine();
            builder.AppendLine("          },");
            builder.AppendLine("          \"display\": {");
            builder.Append("            \"name\": ").Append(JsonString(parameter.Name)).AppendLine(",");
            builder.Append("            \"description\": ").Append(JsonNullableString(parameter.Description)).AppendLine(",");
            builder.Append("            \"group\": ").Append(JsonNullableString(parameter.Group)).AppendLine(",");
            builder.Append("            \"order\": ").Append(parameter.Order).AppendLine(",");
            builder.Append("            \"editorHint\": ").Append(JsonNullableString(parameter.EditorHint)).AppendLine();
            builder.AppendLine("          },");
            builder.AppendLine("          \"runtimeAbi\": {");
            AppendJsonString(builder, "storageClass", parameter.RuntimeAbi.StorageClass, 12, trailingComma: true);
            AppendJsonString(builder, "scalarKind", parameter.RuntimeAbi.ScalarKind, 12, trailingComma: true);
            builder.Append("            \"offset\": ").Append(parameter.RuntimeAbi.Offset).AppendLine(",");
            builder.Append("            \"size\": ").Append(parameter.RuntimeAbi.Size).AppendLine(",");
            builder.Append("            \"alignment\": ").Append(parameter.RuntimeAbi.Alignment).AppendLine(",");
            AppendJsonString(builder, "packing", parameter.RuntimeAbi.Packing, 12, trailingComma: false);
            builder.AppendLine("          },");
            AppendJsonString(builder, "mutability", parameter.Mutability, 10, trailingComma: true);
            builder.AppendLine("          \"bindings\": [");
            for (var bindingIndex = 0; bindingIndex < parameter.Bindings.Length; bindingIndex++)
            {
                builder.Append("            ")
                    .Append(JsonString(parameter.Bindings[bindingIndex]))
                    .AppendLine(bindingIndex + 1 < parameter.Bindings.Length ? "," : string.Empty);
            }
            builder.AppendLine("          ],");
            AppendJsonString(builder, "redaction", parameter.Redaction, 10, trailingComma: true);
            if (parameter.Enum is not null)
            {
                AppendEnum(builder, parameter.Enum);
                builder.AppendLine(",");
            }
            builder.Append("          \"min\": ")
                .Append(JsonNumber(parameter.Min))
                .AppendLine(",");
            builder.Append("          \"max\": ")
                .Append(JsonNumber(parameter.Max))
                .AppendLine();
            builder.Append("        }")
                .AppendLine(index + 1 < parameters.Length ? "," : string.Empty);
        }
        builder.AppendLine("      ]");
    }

    private static void AppendEnum(StringBuilder builder, PassEnumModel contract)
    {
        builder.AppendLine("          \"enum\": {");
        AppendJsonString(builder, "enumTypeGuid", contract.TypeGuid, 12, trailingComma: true);
        AppendJsonString(builder, "underlyingScalar", contract.UnderlyingScalar, 12, trailingComma: true);
        builder.Append("            \"isFlags\": ")
            .Append(contract.IsFlags ? "true" : "false").AppendLine(",");
        builder.Append("            \"allowUnknownNumeric\": ")
            .Append(contract.AllowUnknownNumeric ? "true" : "false").AppendLine(",");
        builder.Append("            \"allowUnknownBits\": ")
            .Append(contract.AllowUnknownBits ? "true" : "false").AppendLine(",");
        builder.Append("            \"allowedMask\": ")
            .Append(contract.IsFlags
                ? contract.AllowedMask.ToString(CultureInfo.InvariantCulture)
                : "null")
            .AppendLine(",");
        builder.AppendLine("            \"members\": [");
        for (var index = 0; index < contract.Members.Length; index++)
        {
            var member = contract.Members[index];
            builder.AppendLine("              {");
            AppendJsonString(builder, "enumMemberGuid", member.Guid, 16, trailingComma: true);
            AppendJsonString(builder, "symbolName", member.SymbolName, 16, trailingComma: true);
            builder.Append("                \"numericValue\": ").Append(member.NumericValue).AppendLine(",");
            AppendJsonString(builder, "displayName", member.DisplayName, 16, trailingComma: true);
            builder.Append("                \"description\": ")
                .Append(JsonNullableString(member.Description)).AppendLine(",");
            builder.Append("                \"order\": ").Append(member.Order).AppendLine(",");
            builder.Append("                \"deprecated\": ")
                .Append(member.Deprecated ? "true" : "false").AppendLine(",");
            builder.Append("                \"replacementMemberGuid\": ")
                .Append(JsonNullableString(member.ReplacementMemberGuid)).AppendLine();
            builder.Append("              }").AppendLine(index + 1 < contract.Members.Length ? "," : string.Empty);
        }
        builder.AppendLine("            ]");
        builder.Append("          }");
    }

    private static string EnumDefaultJson(PassEnumModel contract)
    {
        if (!contract.IsFlags)
        {
            var member = contract.Members.FirstOrDefault(item => item.NumericValue == contract.DefaultRawValue);
            return "{\"kind\":\"ENUM\",\"enumTypeGuid\":" + JsonString(contract.TypeGuid) +
                ",\"memberGuid\":" + JsonNullableString(member?.Guid) +
                ",\"rawValue\":" + contract.DefaultRawValue.ToString(CultureInfo.InvariantCulture) + "}";
        }

        var selected = SelectedFlagMembers(contract)
            .Select(static member => member.Guid)
            .OrderBy(static guid => guid, StringComparer.Ordinal)
            .ToArray();
        return "{\"kind\":\"FLAGS\",\"enumTypeGuid\":" + JsonString(contract.TypeGuid) +
            ",\"selectedMemberGuids\":[" + string.Join(",", selected.Select(JsonString)) +
            "],\"rawValue\":" + contract.DefaultRawValue.ToString(CultureInfo.InvariantCulture) + "}";
    }

    private static IEnumerable<PassEnumMemberModel> SelectedFlagMembers(PassEnumModel contract)
    {
        var exact = contract.Members
            .OrderBy(static member => member.Order)
            .ThenBy(static member => member.SymbolName, StringComparer.Ordinal)
            .FirstOrDefault(member => member.NumericValue == contract.DefaultRawValue);
        if (exact is not null) return [exact];

        ulong widthMask = contract.UnderlyingScalar switch
        {
            "I8" or "U8" => byte.MaxValue,
            "I16" or "U16" => ushort.MaxValue,
            _ => uint.MaxValue,
        };
        ulong raw = unchecked((ulong)contract.DefaultRawValue) & widthMask;
        return contract.Members.Where(member =>
        {
            ulong bits = unchecked((ulong)member.NumericValue) & widthMask;
            return bits != 0 && (bits & (bits - 1)) == 0 && (raw & bits) == bits;
        });
    }

    private static string RelativeSourcePath(string sourcePath, string? projectDirectory)
    {
        if (string.IsNullOrWhiteSpace(sourcePath))
        {
            return string.Empty;
        }
        if (!Path.IsPathRooted(sourcePath) || string.IsNullOrWhiteSpace(projectDirectory))
        {
            return sourcePath.Replace('\\', '/');
        }

        var root = Path.GetFullPath(projectDirectory)
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) + Path.DirectorySeparatorChar;
        var source = Path.GetFullPath(sourcePath);
        var comparison = Path.DirectorySeparatorChar == '\\'
            ? StringComparison.OrdinalIgnoreCase
            : StringComparison.Ordinal;
        return source.StartsWith(root, comparison)
            ? source.Substring(root.Length).Replace('\\', '/')
            : source.Replace('\\', '/');
    }

    private static string JsonNumber(double? value)
        => value?.ToString("R", CultureInfo.InvariantCulture) ?? "null";

    private static string JsonNullableString(string? value)
        => value is null ? "null" : JsonString(value);

    private static void AppendJsonString(
        StringBuilder builder,
        string name,
        string value,
        int indentation,
        bool trailingComma)
    {
        builder.Append(' ', indentation)
            .Append(JsonString(name))
            .Append(": ")
            .Append(JsonString(value))
            .AppendLine(trailingComma ? "," : string.Empty);
    }

    private static string JsonString(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '\b':
                    builder.Append("\\b");
                    break;
                case '\f':
                    builder.Append("\\f");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    if (character < ' ')
                    {
                        builder.Append("\\u")
                            .Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(character);
                    }
                    break;
            }
        }
        return builder.Append('"').ToString();
    }

}
