using System.Collections.Immutable;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Feather.Generators.Diagnostics;
using Feather.Generators.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Feather.Generators;

internal sealed record PassManifestOptions(
    string? ProjectDirectory,
    string AssemblyPath,
    string FeirDirectory)
{
    public static PassManifestOptions Create(AnalyzerConfigOptions options)
    {
        options.TryGetValue("build_property.ProjectDir", out var projectDirectory);
        options.TryGetValue("build_property.FeatherAssemblyPath", out var assemblyPath);
        options.TryGetValue("build_property.FeatherFeirDirectory", out var feirDirectory);

        assemblyPath = string.IsNullOrWhiteSpace(assemblyPath)
            ? "__FEATHER_ASSEMBLY_PATH__"
            : assemblyPath;
        feirDirectory = string.IsNullOrWhiteSpace(feirDirectory)
            ? "__FEATHER_FEIR_DIRECTORY__"
            : feirDirectory;

        return new PassManifestOptions(
            NullIfWhiteSpace(projectDirectory),
            NormalizePath(assemblyPath!),
            NormalizePath(feirDirectory!));
    }

    private static string? NullIfWhiteSpace(string? value)
        => string.IsNullOrWhiteSpace(value) ? null : value;

    private static string NormalizePath(string value)
        => value.Replace('\\', '/');
}

internal static class PassManifestWriter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<PassModel> models,
        PassManifestOptions options)
    {
        if (models.IsDefaultOrEmpty)
        {
            return;
        }

        var validPasses = Validate(context, models)
            .OrderBy(static pass => pass.Guid, StringComparer.Ordinal)
            .ToImmutableArray();
        var manifest = BuildManifest(validPasses, options);
        var manifestLiteral = Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
            manifest,
            quote: true);
        var manifestBase64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(manifest));
        var base64Literal = Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
            manifestBase64,
            quote: true);

        context.AddSource(
            "Feather.PassManifest.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated/>
                #nullable enable
                [assembly: global::System.Reflection.AssemblyMetadataAttribute("Feather.PassManifest", {{base64Literal}})]

                namespace Feather.RenderGraph.Generated;

                internal static class FeatherPassManifest
                {
                    internal const string Json = {{manifestLiteral}};
                }
                """,
                Encoding.UTF8));

    }

    private static IEnumerable<PassModel> Validate(
        SourceProductionContext context,
        ImmutableArray<PassModel> models)
    {
        var passGuids = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var model in models)
        {
            if (!TryNormalizeGuid(context, model.Guid, model.TypeName, model.Location, out var passGuid))
            {
                continue;
            }
            if (!passGuids.Add(passGuid))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.RenderGraphGuidDuplicate,
                    model.Location,
                    passGuid,
                    "the render graph"));
                continue;
            }
            if (!model.ImplementsRenderPass)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    FeatherDiagnostics.RenderPassContractInvalid,
                    model.Location,
                    model.TypeName));
                continue;
            }

            var memberGuids = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var valid = true;
            var inputs = NormalizeSockets(context, model, model.Inputs, memberGuids, ref valid);
            var outputs = NormalizeSockets(context, model, model.Outputs, memberGuids, ref valid);
            var parameters = ImmutableArray.CreateBuilder<PassParameterModel>();
            foreach (var parameter in model.Parameters)
            {
                if (!TryNormalizeGuid(
                        context,
                        parameter.Guid,
                        $"{model.TypeName}.{parameter.Name}",
                        parameter.Location,
                        out var parameterGuid))
                {
                    valid = false;
                    continue;
                }
                if (!memberGuids.Add(parameterGuid))
                {
                    ReportDuplicate(context, parameterGuid, model, parameter.Location);
                    valid = false;
                    continue;
                }
                parameters.Add(parameter with { Guid = parameterGuid });
            }

            if (valid)
            {
                yield return model with
                {
                    Guid = passGuid,
                    Inputs = inputs,
                    Outputs = outputs,
                    Parameters = parameters.ToImmutable()
                };
            }
        }
    }

    private static ImmutableArray<PassSocketModel> NormalizeSockets(
        SourceProductionContext context,
        PassModel model,
        ImmutableArray<PassSocketModel> sockets,
        HashSet<string> memberGuids,
        ref bool valid)
    {
        var result = ImmutableArray.CreateBuilder<PassSocketModel>();
        foreach (var socket in sockets)
        {
            if (!TryNormalizeGuid(
                    context,
                    socket.Guid,
                    $"{model.TypeName}.{socket.Name}",
                    socket.Location,
                    out var socketGuid))
            {
                valid = false;
                continue;
            }
            if (!memberGuids.Add(socketGuid))
            {
                ReportDuplicate(context, socketGuid, model, socket.Location);
                valid = false;
                continue;
            }
            result.Add(socket with { Guid = socketGuid });
        }
        return result.ToImmutable();
    }

    private static bool TryNormalizeGuid(
        SourceProductionContext context,
        string value,
        string owner,
        Location location,
        out string normalized)
    {
        if (Guid.TryParseExact(value, "D", out var guid))
        {
            normalized = guid.ToString("D");
            return true;
        }

        context.ReportDiagnostic(Diagnostic.Create(
            FeatherDiagnostics.RenderGraphGuidInvalid,
            location,
            value,
            owner));
        normalized = string.Empty;
        return false;
    }

    private static void ReportDuplicate(
        SourceProductionContext context,
        string guid,
        PassModel model,
        Location location)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            FeatherDiagnostics.RenderGraphGuidDuplicate,
            location,
            guid,
            model.TypeName));
    }

    private static string BuildManifest(
        ImmutableArray<PassModel> passes,
        PassManifestOptions options)
    {
        var contentForHash = BuildManifest(passes, options, buildId: string.Empty);
        using var sha256 = SHA256.Create();
        var hash = sha256.ComputeHash(Encoding.UTF8.GetBytes(contentForHash));
        var buildId = "sha256:" + BitConverter.ToString(hash).Replace("-", string.Empty).ToLowerInvariant();
        return BuildManifest(passes, options, buildId);
    }

    private static string BuildManifest(
        ImmutableArray<PassModel> passes,
        PassManifestOptions options,
        string buildId)
    {
        var builder = new StringBuilder();
        builder.AppendLine("{");
        builder.AppendLine("  \"schemaVersion\": 1,");
        AppendJsonString(builder, "buildId", buildId, 2, trailingComma: true);
        AppendJsonString(builder, "assemblyPath", options.AssemblyPath, 2, trailingComma: true);
        AppendJsonString(builder, "feirDirectory", options.FeirDirectory, 2, trailingComma: true);
        builder.AppendLine("  \"passes\": [");
        for (var index = 0; index < passes.Length; index++)
        {
            AppendPass(builder, passes[index], options, index + 1 < passes.Length);
        }
        builder.AppendLine("  ]");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendPass(
        StringBuilder builder,
        PassModel pass,
        PassManifestOptions options,
        bool trailingComma)
    {
        builder.AppendLine("    {");
        AppendJsonString(builder, "passGuid", pass.Guid, 6, trailingComma: true);
        AppendJsonString(builder, "typeName", pass.TypeName, 6, trailingComma: true);
        AppendJsonString(builder, "displayName", pass.DisplayName, 6, trailingComma: true);
        AppendJsonString(builder, "category", pass.Category, 6, trailingComma: true);
        builder.Append("      \"version\": ").Append(pass.Version).AppendLine(",");
        AppendJsonString(builder, "assemblyPath", options.AssemblyPath, 6, trailingComma: true);
        AppendJsonString(
            builder,
            "feirPath",
            options.FeirDirectory.TrimEnd('/') + "/" + pass.Guid + ".feir",
            6,
            trailingComma: true);
        builder.AppendLine("      \"source\": {");
        AppendJsonString(
            builder,
            "path",
            RelativeSourcePath(pass.SourcePath, options.ProjectDirectory),
            8,
            trailingComma: true);
        builder.Append("        \"line0\": ").Append(pass.SourceLine).AppendLine(",");
        builder.Append("        \"column0\": ").Append(pass.SourceColumn).AppendLine();
        builder.AppendLine("      },");
        AppendSockets(builder, "inputs", pass.Inputs, trailingComma: true);
        AppendSockets(builder, "outputs", pass.Outputs, trailingComma: true);
        AppendParameters(builder, pass.Parameters);
        builder.Append("    }");
        builder.AppendLine(trailingComma ? "," : string.Empty);
    }

    private static void AppendSockets(
        StringBuilder builder,
        string name,
        ImmutableArray<PassSocketModel> sockets,
        bool trailingComma)
    {
        builder.Append("      ").Append(JsonString(name)).AppendLine(": [");
        for (var index = 0; index < sockets.Length; index++)
        {
            var socket = sockets[index];
            builder.AppendLine("        {");
            AppendJsonString(builder, "socketGuid", socket.Guid, 10, trailingComma: true);
            AppendJsonString(builder, "name", socket.Name, 10, trailingComma: true);
            AppendJsonString(builder, "resourceKind", socket.ResourceKind, 10, trailingComma: true);
            AppendJsonString(builder, "format", socket.Format, 10, trailingComma: true);
            AppendJsonString(builder, "access", socket.Access, 10, trailingComma: false);
            builder.Append("        }").AppendLine(index + 1 < sockets.Length ? "," : string.Empty);
        }
        builder.Append("      ]").AppendLine(trailingComma ? "," : string.Empty);
    }

    private static void AppendParameters(
        StringBuilder builder,
        ImmutableArray<PassParameterModel> parameters)
    {
        builder.AppendLine("      \"parameters\": [");
        for (var index = 0; index < parameters.Length; index++)
        {
            var parameter = parameters[index];
            builder.AppendLine("        {");
            AppendJsonString(builder, "parameterGuid", parameter.Guid, 10, trailingComma: true);
            AppendJsonString(builder, "name", parameter.Name, 10, trailingComma: true);
            AppendJsonString(builder, "type", parameter.Type, 10, trailingComma: true);
            builder.Append("          \"defaultValue\": ")
                .Append(parameter.DefaultValueJson ?? "null")
                .AppendLine(",");
            builder.Append("          \"min\": ")
                .Append(JsonNumber(parameter.Min))
                .AppendLine(",");
            builder.Append("          \"max\": ")
                .Append(JsonNumber(parameter.Max))
                .AppendLine();
            builder.Append("        }")
                .AppendLine(index + 1 < parameters.Length ? "," : string.Empty);
        }
        builder.AppendLine("      ]");
    }

    private static string RelativeSourcePath(string sourcePath, string? projectDirectory)
    {
        if (string.IsNullOrWhiteSpace(sourcePath))
        {
            return string.Empty;
        }
        if (!Path.IsPathRooted(sourcePath) || string.IsNullOrWhiteSpace(projectDirectory))
        {
            return sourcePath.Replace('\\', '/');
        }

        var root = Path.GetFullPath(projectDirectory)
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) + Path.DirectorySeparatorChar;
        var source = Path.GetFullPath(sourcePath);
        var comparison = Path.DirectorySeparatorChar == '\\'
            ? StringComparison.OrdinalIgnoreCase
            : StringComparison.Ordinal;
        return source.StartsWith(root, comparison)
            ? source.Substring(root.Length).Replace('\\', '/')
            : source.Replace('\\', '/');
    }

    private static string JsonNumber(double? value)
        => value?.ToString("R", CultureInfo.InvariantCulture) ?? "null";

    private static void AppendJsonString(
        StringBuilder builder,
        string name,
        string value,
        int indentation,
        bool trailingComma)
    {
        builder.Append(' ', indentation)
            .Append(JsonString(name))
            .Append(": ")
            .Append(JsonString(value))
            .AppendLine(trailingComma ? "," : string.Empty);
    }

    private static string JsonString(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '\b':
                    builder.Append("\\b");
                    break;
                case '\f':
                    builder.Append("\\f");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    if (character < ' ')
                    {
                        builder.Append("\\u")
                            .Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(character);
                    }
                    break;
            }
        }
        return builder.Append('"').ToString();
    }

}
